# This is a basic workflow to help you get started with Actions

name: defualt

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # RUNNING
      - name: Run a one-line script
        run: echo Hello, world!

      # STARTING THE MC
      - name: Run a multi-line script
        run: |
          wget https://dl.google.com/linux/direct/chrome-remote-desktop_current_amd64.deb
          sudo apt update
          sudo apt install --assume-yes \
          --with-source=chrome-remote-desktop_current_amd64.deb \
          chrome-remote-desktop
          sudo DEBIAN_FRONTEND=noninteractive \
          apt install --assume-yes xfce4 desktop-base
          echo "xfce4-session" > ~/.chrome-remote-desktop-session
          sudo apt install --assume-yes xscreensaver
          sudo systemctl disable lightdm.service
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install --assume-yes  google-chrome-stable \
          --with-source=google-chrome-stable_current_amd64.deb
          
   
